const fs = require('fs');
let c = fs.readFileSync('app/numerology-guide/articles/compatibility-pairs/page.tsx', 'utf8');
const OPENING = /  return \(\s*<div className=\"min-h-screen bg-gradient-to-b from-violet-50 to-white\">\s*<div className=\"max-w-lg mx-auto px-4 py-8 space-y-8\">\s*<div className=\"flex gap-3\">\s*<Link[^>]*>[\s\S]*?<\/Link>\s*<Link[^>]*>[\s\S]*?<\/Link>\s*<\/div>\s*<article>/;
const OPENING_REPL = '  return (\n    <>\n        <article>';
const CLOSING = /(<AdBanner \/>\s*<RakutenWidget \/>)\s*<\/div>\s*<\/div>\s*\);/;
const CLOSING_REPL = '\\n    </>\n  );';
c = c.replace(OPENING, OPENING_REPL);
c = c.replace(CLOSING, CLOSING_REPL);
c = c.replace(/text-violet-500(?= text-xs)/g, 'text-violet-400');
c = c.replace(/text-gray-500(?= text-xs)/g, 'text-slate-400');
c = c.replace(/text-violet-900/g, 'text-white');
c = c.replace(/text-gray-600/g, 'text-slate-300');
c = c.replace(/text-violet-800 border-b-2 border-violet-200/g, 'text-white border-b-2 border-violet-600\/50');
c = c.replace(/rounded-2xl border-2 border-violet-100 bg-white p-5/g, 'rounded-2xl border-2 border-violet-600\/50 bg-white\/10 p-5');
c = c.replace(/text-violet-800/g, 'text-white');
c = c.replace(/text-violet-600/g, 'text-violet-400');
c = c.replace(/text-gray-700/g, 'text-slate-200');
c = c.replace(/text-violet-700/g, 'text-violet-400');
c = c.replace(/bg-violet-50 border border-violet-100/g, 'bg-white\/10 border border-violet-600\/30');
c = c.replace(/bg-gradient-to-r from-violet-500 to-purple-600 text-white font-bold text-center shadow-md hover:opacity-95 transition-opacity/g, 'bg-violet-600 text-white font-bold text-center shadow-md hover:bg-violet-700 transition-colors');
fs.writeFileSync('app/numerology-guide/articles/compatibility-pairs/page.tsx', c, 'utf8');
console.log('Updated compatibility-pairs');
